language: csharp
sudo: required
dist: xenial
mono: none
dotnet: 2.2

os:
  - linux

branches:
  only:
  - master
  - dev

script:
  - dotnet build
  - dotnet test test/ArgsMapper.Test/ArgsMapper.Test.csproj
