version: 0.1.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release

branches:
  only:
    - master
    - dev
    - appveyor-integration

test: off

build:
  verbosity: minimal

build_script:
- ps: ./build.ps1
