version: 0.1.{build}
skip_tags: true
image: Visual Studio 2019 Preview
configuration: Release

branches:
  only:
    - master
    - dev

test: off

build:
  verbosity: minimal

build_script:
- ps: ./build.ps1
